---
title: "A League of Data (JSC370 Final Project)"
author: "Mark JP Sanchez"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

## What is League of Legends

League of Legends is a hugely popular video game that rakes in billions of dollars a year and is easily one of the most popular and influential games in the world. The success of the game has even spawned a successful e-sports scene, a k-pop band, and even a critically acclaimed Netflix show. All of this, spawning from an online 5 vs. 5 competitive MOBA game. A MOBA game effectively being a game such that two teams face off head-to-head in a match. Each player chooses a character, in League of Legends they are called Champions, to play as and each character has a unique set of skills. During the game, each player attempts to level up their character, accrue money to spend on items, destroy enemy towers and escort their minions to the enemy base. The objective of the game is to destroy your opponent's base but to do so, you need to power up and work with your team to both infiltrate their base and protect yours over the course of 20 minutes to an hour. 

Evidently. one thing that makes the game so much fun is all the moving parts and decisions a player can make to influence a match. Some decisions include what champion to choose, what items to buy, and what objective to focus on. Unfortunately, all of these factors and decisions can overwhelm new and existing players, and with the main objective obviously being to win the game, it would be nice to now what kind of decisions actually influence those wins.

## The Dataset

The data set was taken from the RIOT api and contains data from League of Legends matches. The data collected contains info such as how long the matches were, what champions each player played, how much damage each player did, and what side objectives the players took. The data was given in JSON format which I had to turn into nice R data frames.

One issue that arose from gathering match data from the RIOT api was that there was no proper endpoint for gathering random matches. The main way to gather matches was to call an endpoint that gave you a list of past matches of a specific player. The problem with this is that if I collected all of my match data from this list of matches, then I would have a confounding variable being this one player. I want to make my data between matches as independent as possible. Luckily, each match consists of 10 players so I can recursively gather matches of each player in the current match. Using this method, I gathered the my match data by first gathering a few thousand player ids by recursively checking the players in a given player's latest match. I then get the latest match before a previous date of each player. My chosen date was Valentines day which was a week before I gathered my data. There was also a large update to the game on January 7th, 2022 so we need to make sure our matches don't come before then. This should give me a list of matches that has little overlap in players.

Calling the match data api from RIOT gives you a lot of variables to work with. Especially since each player in the match have tens of different variable attached to them. With 10 players per game, that is a lot of data to work with. Since we are looking at the decisions each player makes on their own, we will take the data and split it up into 2 different datasets. The first dataset will contain match metadata such as when the match was created and how long the match was. The second dataset contains data on each player during a match. So each observation in that player dataset will be corresponding to data from a player in a match. This data will include things like how much damage they did, how many kills they got and how much gold they made.

With the methodologies I listed above I ran my code and let the program run for a few hours. This long waiting time was due to the rate limit imposed by the RIOT api of a max of 100 requests per 2 minutes. In the end we collected a dataset of 9400 matches.
